-- MySQL Script generated by MySQL Workbench
-- seg 06 jul 2020 17:19:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema qt_gostoso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qt_gostoso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qt_gostoso` ;
USE `qt_gostoso` ;

-- -----------------------------------------------------
-- Table `qt_gostoso`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qt_gostoso`.`receita` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `conteudo` TEXT NOT NULL,
  `thumb` VARCHAR(150) NULL,
  `data_publicacao` DATETIME NOT NULL,
  `tags` VARCHAR(156) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
